homeassistant:
  # Name of the location where Home Assistant is running
  name: Oxsana
  # Location required to calculate the time the sun rises and sets
  latitude: 53.614122
  longitude: -1.832874
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 217
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - cloud_cover
      - minutely_summary
      - hourly_summary
      - precip_intensity_max
  - platform: speedtest
    minute: 5
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - download

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    home_interval: 10
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False

mqtt:
  broker: localhost
  username: !secret mqtt_user
  password: !secret mqtt_pass

# Text to speech
tts:
  - platform: google

# Cloud
# cloud:

http:
#  api_password: !secret http_password
#  ssl_certificate: /etc/letsencrypt/live/smithhome.network/fullchain.pem
#  ssl_key: /etc/letsencrypt/live/smithhome.network/privkey.pem
#  base_url: smithhome.network

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
